server:
  port: 8991

spring:
  application:
    name: LUCKYGOU-ZUUL


#路由配置
zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: LUCKYGOU-PLAT
      path: /plat/**
    product:
      serviceId: LUCKYGOU-PRODUCT
      path: /product/**
    common:
      serviceId: LUCKYGOU-COMMON
      path: /common/**
  prefix: /services