server:
  port: 7777
spring:
  application:
    name: LUCKYGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///luckygou-product
    username: root
    password: 19970702
mybatis-plus:
    mapper-locations: classpath*:cn/itsource/luckygou/mapper/*Mapper.xml